@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

ReserveMate *-right-> "1" UniqueReservationList
ReserveMate *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueReservationList
UniqueTagList -[hidden]down- UniqueReservationList

UniqueTagList -right-> "*" Tag
UniqueReservationList -right-> Reservation

Reservation -up-> "*" Tag

Reservation *--> Name
Reservation *--> Phone
Reservation *--> Email
Reservation *--> Number_of_Diners
Reservation *--> Date_Time
@enduml
