@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command "clear cfm"

package States <<rectangle>> {
    class State1 as "<u>rm0:ReserveMate</u>"
    class State2 as "<u>rm1:ReserveMate</u>"
    class State3 as "<u>rm2:ReserveMate</u>"
}


State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

class Pointer as "Current State" #FFFFFF

Pointer -up-> State3
note right on link: State rm2 deleted.
@end
